[workspace]
members = ["programs/*", "clients/rust/*", "tools/*", "observability/indexer"]

[workspace.dependencies]
solana-client = "=1.16.19"
solana-sdk = "=1.16.19"
solana-logger = "=1.16.19"
solana-program = "=1.16.19"
solana-program-test = "=1.16.19"
solana-account-decoder = "=1.16.19"
solana-measure = "=1.16.19"
solana-metrics = "=1.16.19"
solana-transaction-status = "=1.16.19"
spl-token = "4.0.0"
spl-associated-token-account = "2.2.0"

anchor-lang = "0.28.0"
anchor-spl = "0.28.0"
anchor-client = "0.28.0"

switchboard-v2 = "0.4.0"
pyth-sdk-solana = "0.8.0"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
